### ISSUE TITLE
Cannot download wallpaper

### ISSUE THREAD

**Issue by github-raiyan** [losbiw/erin#11]
Every time image downloading is paused at a level.
system: Zorin os  15.3
![image](https://user-images.githubusercontent.com/45367929/120682353-3069c300-c4be-11eb-91ee-d000400e19f0.png)
![image](https://user-images.githubusercontent.com/45367929/120682739-9f471c00-c4be-11eb-8930-9ece1b9a0fbd.png)

**Comment by losbiw** [comment]
Fixed in 4d5ccb1efc0e88d4c131870d51e96ea7c8e3958e
