### ISSUE TITLE
Credit card number on landing page?

### ISSUE THREAD

**Issue by hoangvu12** [losbiw/erin#14]
Uh I don't think putting your credit card number in your landing page is a good idea...

**Comment by hoangvu12** [comment]
> I don't see it as a problem whatsoever since it doesn't reveal any confidential data like cvv or expiration date. Could you please elaborate?

That's maybe right but someone can just bruteforce your expiration date. And now there are still websites allow credit card payment without cvv. (like Amazon).

**Comment by losbiw** [comment]
> > I don't see it as a problem whatsoever since it doesn't reveal any confidential data like cvv or expiration date. Could you please elaborate?
> 
> That's maybe right but someone can just bruteforce your expiration date. And now there are still websites allow credit card payment without cvv. (like Amazon).

Yes, but either way all the payments require confirmation through my card's vendor app (which is the case in any other bank in this world this way or another), so once again, there is literally no way of magically stealing money from anyone's card without knowing certain confidential data, which credit card's number isn't
